#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

django-admin compilemessages
python /app/manage.py collectstatic --noinput
python /app/manage.py compress --force
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
